[package]
name = "rust-tester"
version = "0.1.0"
authors = ["Skalman <skalman@riseup.net>"]
edition = "2018"

[dependencies]
base64 = "*"
clap = "*"
parity-codec={path = "../../../implementations/rust/parity-codec"}

[[bin]]
name = "scale_codec"
path = "src/scale_codec.rs"
